### ISSUE TITLE
BuildError:  Failed to build this package.

### ISSUE THREAD

**Issue by jbadan** [pastelsky/bundlephobia#189]
## Package name

fundamental-styles@0.2.0-rc.21 (https://bundlephobia.com/result?p=fundamental-styles@0.2.0-rc.21) - use 0.2.0-rc.21 as previous versions had an incorrect entry point.

### Entire (stringified) error that I see in my browser console

```
/tmp/tmp-build/packages/build-fundamental-styles@0.2.0-rc.21-N4f/node_modules/fundamental-styles/dist/fundamental-styles.css Module build failed (from ./build-service/node_modules/mini-css-extract-plugin/dist/loader.js): ModuleNotFoundError: Module not found: Error: Can't resolve 'file-loader' in '/var/www/bundlephobia' at factory.create (/var/www/bundlephobia/build-service/node_modules/webpack/lib/Compilation.js:821:10) at factory (/var/www/bundlephobia/build-service/node_modules/webpack/lib/NormalModuleFactory.js:397:22) at resolver (/var/www/bundlephobia/build-service/node_modules/webpack/lib/NormalModuleFactory.js:130:21) at asyncLib.parallel (/var/www/bundlephobia/build-service/node_modules/webpack/lib/NormalModuleFactory.js:337:24) at /var/www/bundlephobia/build-service/node_modules/neo-async/async.js:2825:7 at /var/www/bundlephobia/build-service/node_modules/neo-async/async.js:6886:13 at /var/www/bundlephobia/build-service/node_modules/neo-async/async.js:2825:7 at done (/var/www/bundlephobia/build-service/node_modules/neo-async/async.js:2922:13) at resolver.resolve (/var/www/bundlephobia/build-service/node_modules/webpack/lib/NormalModuleFactory.js:447:23) at doResolve (/var/www/bundlephobia/build-service/node_modules/enhanced-resolve/lib/Resolver.js:184:12) at hook.callAsync (/var/www/bundlephobia/build-service/node_modules/enhanced-resolve/lib/Resolver.js:238:5) at _fn0 (eval at create (/var/www/bundlephobia/build-service/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1) at resolver.doResolve (/var/www/bundlephobia/build-service/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5) at hook.callAsync (/var/www/bundlephobia/build-service/node_modules/enhanced-resolve/lib/Resolver.js:238:5) at _fn0 (eval at create (/var/www/bundlephobia/build-service/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1) at hook.callAsync (/var/www/bundlephobia/build-service/node_modules/enhanced-resolve/lib/Resolver.js:238:5) @ /tmp/tmp-build/packages/build-fundamental-styles@0.2.0-rc.21-N4f/index.js 1:10-39
```

**Comment by pastelsky** [comment]
Bundlephobia picks the `latest` tagged version unless a specific version is specified. I don't think I understand what you intend to convey here since —
bundlephobia.com/result?p=fundamental-styles@0.2.0-rc.21
builds just fine.

**Comment by jbadan** [comment]
@pastelsky It didn't build in 2019 when this issue was reported. 
Closing as it's fixed now, thanks!
