### ISSUE TITLE
BuildError: nmr-displayer fails to build (no appropriate error)

### ISSUE THREAD

**Issue by lpatiny** [pastelsky/bundlephobia#325]
### Entire (stringified) error that I see in my browser console

```
Uncaught DOMException: Failed to execute 'getTotalLength' on 'SVGGeometryElement': This element is non-rendered element.
    at se (https://bundlephobia.com/_next/static/zl6uIeydwIzpietGs76H6/pages/result.js:1:38015)
    at Function.Ie.setDashoffset (https://bundlephobia.com/_next/static/zl6uIeydwIzpietGs76H6/pages/result.js:1:46135)
    at Ne.strokeDashoffset (https://bundlephobia.com/_next/static/zl6uIeydwIzpietGs76H6/pages/result.js:1:51350)
    at $ (https://bundlephobia.com/_next/static/zl6uIeydwIzpietGs76H6/pages/result.js:1:36148)
    at https://bundlephobia.com/_next/static/zl6uIeydwIzpietGs76H6/pages/result.js:1:40441
    at Array.map (<anonymous>)
    at https://bundlephobia.com/_next/static/zl6uIeydwIzpietGs76H6/pages/result.js:1:40418
    at https://bundlephobia.com/_next/static/zl6uIeydwIzpietGs76H6/pages/result.js:1:40546
    at Array.map (<anonymous>)
    at me (https://bundlephobia.com/_next/static/zl6uIeydwIzpietGs76H6/pages/result.js:1:40322)
```

**Comment by pastelsky** [comment]
I don't see this error for the same package. Could you add a gif of the bug as well information about your OS / Browser / Browser Version to help me debug this?

**Comment by lpatiny** [comment]
Actually it works now. Could it be related to your last commit ?

I'm working on OsX 10.14.5 using google chrome: Version 80.0.3987.149 (Official Build) (64-bit

**Comment by pastelsky** [comment]
There haven't been any recent commits. This could be a race condition. Leaving this issue open in case you manage to replicate this in the future.

**Comment by pastelsky** [comment]
I just hit this issue in local dev, and this will be fixed in the next release. Thanks again.
