### ISSUE TITLE
BuildError

### ISSUE THREAD

**Issue by arturoromeroslc** [pastelsky/bundlephobia#345]
## Type

Bug

## Package name

web-vitals

### Entire error (stringified) I see in my browser console
```
{
  "error": {
    "code": "BuildError",
    "message": "Failed to build this package.",
    "details": {
      "name": "BuildError",
      "originalError": [
        "main.bundle.js from Terser\n\"Export\" statement may only appear at the top level [main.bundle.js:11,2531]\n    at Q (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:19191)\n    at An.visit (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:111249)\n    at An._visit (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:75539)\n    at AST_Export._walk (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:64888)\n    at Ee (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:52427)\n    at AST_Function.<anonymous> (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:58400)\n    at /var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:75562\n    at An.visit (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:109929)\n    at An._visit (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:75539)\n    at AST_Function._walk (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:58285)"
      ]
    }
  }
}
```

**Comment by pastelsky** [comment]
`web-vitals` builds fine now. Thanks for the bug report.
