### ISSUE TITLE
BuildError: object-visualizer fails to build

### ISSUE THREAD

**Issue by iendeavor** [pastelsky/bundlephobia#382]
### Entire (stringified) error that I see in my browser console

```
"main.bundle.js from Terser
"Import" statement may only appear at the top level [main.bundle.js:11,0]
    at Q (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:19191)
    at An.visit (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:111249)
    at An._visit (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:75539)
    at AST_Import._walk (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:64206)
    at Ee (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:52427)
    at AST_Function.<anonymous> (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:58400)
    at /var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:75562
    at An.visit (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:109929)
    at An._visit (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:75539)
    at AST_Function._walk (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:58285)"
```

**Comment by pastelsky** [comment]
`object-visualizer` builds fine now. Thanks for submitting a bug report.
