### ISSUE TITLE
main.bundle.js from Terser "Export" statement may only appear at the top level

### ISSUE THREAD

**Issue by elalish** [pastelsky/bundlephobia#383]
## Type

Bug

## Package name

@google/model-viewer

### Entire error (stringified) I see in my browser console

```
BuildError
Failed to build this package.

 Stacktrace
main.bundle.js from Terser "Export" statement may only appear at the top level [main.bundle.js:1020,23422] at Q (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:19191) at An.visit (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:111249) at An._visit (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:75539) at AST_Export._walk (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:64888) at Ee (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:52427) at AST_Function.<anonymous> (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:58400) at /var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:75562 at An.visit (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:109929) at An._visit (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:75539) at AST_Function._walk (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:58285)
```

### Notes

Once upon a time this worked fine for our package, and I'm not entirely sure when it broke. Obviously everything builds fine for us locally. In fact we have no dependencies, so it doesn't seem like a build step should really be necessary at all, since our package is already bundled and minified.

**Comment by mrdoob** [comment]
https://bundlephobia.com/result?p=@google/model-viewer

**Comment by HackbrettXXX** [comment]
Same issue with jspdf: https://bundlephobia.com/result?p=jspdf@2.1.1

I created an issue in the package-build-stats repo: https://github.com/pastelsky/package-build-stats/issues/26

**Comment by pastelsky** [comment]
This should be fixed now, thanks to @HackbrettXXX
