### ISSUE TITLE
Server: ERR_SOCKET_BAD_PORT

### ISSUE THREAD

**Issue by pauldraper** [pastelsky/bundlephobia#397]
**Describe the bug**

Server crashes whenever looking up a pacakge.

**To Reproduce**

```
yarn start
```

Navigate to http://localhost:5000/result?p=moment

**Expected behavior**

Size of package is show

**Actual behavior**

Server crashes with

```
> Ready on http://localhost:5000
  bp:request resolved to moment@2.28.0 +0ms
  bp:cache get package moment@2.28.0 +0ms
dgram.js:342
    throw new ERR_SOCKET_BAD_PORT(port);
    ^

RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received 0.
    at validatePort (dgram.js:342:11)
    at Socket.send (dgram.js:595:12)
    at graylog.send (/home/paul/dev/pastelsky/bundlephobia/node_modules/graylog2/graylog.js:265:12)
    at sendPayload (/home/paul/dev/pastelsky/bundlephobia/node_modules/graylog2/graylog.js:181:25)
    at graylog.log [as _log] (/home/paul/dev/pastelsky/bundlephobia/node_modules/graylog2/graylog.js:246:7)
    at graylog.info (/home/paul/dev/pastelsky/bundlephobia/node_modules/graylog2/graylog.js:106:17)
    at Immediate._onImmediate (/home/paul/dev/pastelsky/bundlephobia/node_modules/winston-graylog2/lib/winston-graylog2.js:79:50)
    at processImmediate (internal/timers.js:439:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
```

**Comment by pastelsky** [comment]
Closing as completed: the current logger is console-only Winston logging; the old Graylog UDP transport that raised ERR_SOCKET_BAD_PORT is no longer present.
