### ISSUE TITLE
Build error: @ant-design/pro-layout fails to build due to missing less-loader (?)

### ISSUE THREAD

**Issue by extempl** [pastelsky/bundlephobia#461]
### Entire (stringified) error that I see in my console

```
Error [BuildError]: BuildError
    at Object.buildPackage (/Users/extempl/Projects/bundlephobia/node_modules/package-build-stats/build/utils/build.utils.js:184:17)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Object.buildPackageIgnoringMissingDeps (/Users/extempl/Projects/bundlephobia/node_modules/package-build-stats/build/utils/build.utils.js:264:31)
    at async Promise.all (index 1)
    at async AsyncFunction.getPackageStats (/Users/extempl/Projects/bundlephobia/node_modules/package-build-stats/build/getPackageStats.js:64:48) {
  name: 'BuildError',
  originalError: [
    '/tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/SettingDrawer/ThemeColor.less 1:0\n' +
      "Module parse failed: Unexpected character '@' (1:0)\n" +
      'You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n' +
      "> @import './index.less';\n" +
      '| .@{ant-pro-setting-drawer}-content {\n' +
      '|   .theme-color {\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/SettingDrawer/ThemeColor.js 10:0-27\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/SettingDrawer/index.js\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/index.js\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/index.js',
    '/tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/SettingDrawer/index.less 1:0\n' +
      "Module parse failed: Unexpected character '@' (1:0)\n" +
      'You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n' +
      "> @import '~antd/es/style/themes/default.less';\n" +
      '| \n' +
      "| @ant-pro-setting-drawer: ~'@{ant-prefix}-pro-setting-drawer';\n" +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/SettingDrawer/index.js 34:0-22\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/index.js\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/index.js',
    '/tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/BasicLayout.less 1:0\n' +
      "Module parse failed: Unexpected character '@' (1:0)\n" +
      'You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n' +
      "> @import '~antd/es/style/themes/default.less';\n" +
      '| \n' +
      "| @basicLayout-prefix-cls: ~'@{ant-prefix}-pro-basicLayout';\n" +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/BasicLayout.js 28:0-28\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/index.js\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/index.js',
    '/tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-utils/es/components/LabelIconTip/index.less 1:0\n' +
      "Module parse failed: Unexpected character '@' (1:0)\n" +
      'You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n' +
      "> @import '~antd/es/style/themes/default.less';\n" +
      '| \n' +
      "| @pro-core-label-tip: ~'@{ant-prefix}-pro-core-label-tip';\n" +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-utils/es/components/LabelIconTip/index.js 9:0-22\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-utils/es/index.js\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/BasicLayout.js\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/index.js\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/index.js',
    '/tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/FooterToolbar/index.less 1:0\n' +
      "Module parse failed: Unexpected character '@' (1:0)\n" +
      'You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n' +
      "> @import '~antd/es/style/themes/default.less';\n" +
      '| \n' +
      "| @pro-footer-bar-prefix-cls: ~'@{ant-prefix}-pro-footer-bar';\n" +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/FooterToolbar/index.js 15:0-22\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/index.js\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/index.js',
    '/tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/GlobalFooter/index.less 1:0\n' +
      "Module parse failed: Unexpected character '@' (1:0)\n" +
      'You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n' +
      "> @import '~antd/es/style/themes/default.less';\n" +
      '| \n' +
      "| @pro-global-footer-prefix-cls: ~'@{ant-prefix}-pro-global-footer';\n" +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/GlobalFooter/index.js 1:0-22\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/Footer.js\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/index.js\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/index.js',
    '/tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/Header.less 1:0\n' +
      "Module parse failed: Unexpected character '@' (1:0)\n" +
      'You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n' +
      "> @import '~antd/es/style/themes/default.less';\n" +
      '| \n' +
      "| @pro-layout-fixed-header-prefix-cls: ~'@{ant-prefix}-pro-fixed-header';\n" +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/Header.js 34:0-23\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/index.js\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/index.js',
    '/tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/PageContainer/index.less 1:0\n' +
      "Module parse failed: Unexpected character '@' (1:0)\n" +
      'You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n' +
      "> @import '~antd/es/style/themes/default.less';\n" +
      '| \n' +
      "| @pro-layout-page-container: ~'@{ant-prefix}-pro-page-container';\n" +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/PageContainer/index.js 25:0-22\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/index.js\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/index.js',
    '/tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-utils/es/components/ListToolBar/index.less 1:0\n' +
      "Module parse failed: Unexpected character '@' (1:0)\n" +
      'You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n' +
      "> @import '~antd/es/style/themes/default.less';\n" +
      '| \n' +
      "| @pro-list-toolbar: ~'@{ant-prefix}-pro-core-toolbar';\n" +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-utils/es/components/ListToolBar/index.js 26:0-22\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-utils/es/index.js\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/BasicLayout.js\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/index.js\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/index.js',
    '/tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/TopNavHeader/index.less 1:0\n' +
      "Module parse failed: Unexpected character '@' (1:0)\n" +
      'You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n' +
      "> @import '~antd/es/style/themes/default.less';\n" +
      "| @import '../BasicLayout.less';\n" +
      '| \n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/TopNavHeader/index.js 29:0-22\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/index.js\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/index.js',
    '/tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/SiderMenu/index.less 1:0\n' +
      "Module parse failed: Unexpected character '@' (1:0)\n" +
      'You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n' +
      "> @import '~antd/es/style/themes/default.less';\n" +
      "| @import '../BasicLayout.less';\n" +
      '| \n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/SiderMenu/SiderMenu.js 17:0-22\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/TopNavHeader/index.js\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/index.js\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/index.js',
    '/tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/GlobalHeader/index.less 1:0\n' +
      "Module parse failed: Unexpected character '@' (1:0)\n" +
      'You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n' +
      "> @import '~antd/es/style/themes/default.less';\n" +
      "| @import '../BasicLayout.less';\n" +
      '| \n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/GlobalHeader/index.js 9:0-22\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/Header.js\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/index.js\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/index.js',
    '/tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/GridContent/GridContent.less 1:0\n' +
      "Module parse failed: Unexpected character '@' (1:0)\n" +
      'You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n' +
      "> @import '~antd/es/style/themes/default.less';\n" +
      "| @pro-layout-grid-content-prefix-cls: ~'@{ant-prefix}-pro-grid-content';\n" +
      '| \n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/GridContent/index.js 1:0-28\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/index.js\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/index.js',
    '/tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-utils/es/components/DropdownFooter/index.less 1:0\n' +
      "Module parse failed: Unexpected character '@' (1:0)\n" +
      'You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n' +
      "> @import (reference) '~antd/lib/style/themes/default';\n" +
      '| \n' +
      "| @pro-core-dropdown-footer: ~'@{ant-prefix}-pro-core-dropdown-footer';\n" +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-utils/es/components/DropdownFooter/index.js 7:0-22\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-utils/es/components/FiledDropdown/index.js\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-utils/es/index.js\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/BasicLayout.js\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/index.js\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/index.js',
    '/tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-utils/es/components/FiledDropdown/index.less 1:0\n' +
      "Module parse failed: Unexpected character '@' (1:0)\n" +
      'You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n' +
      "> @import (reference) '~antd/lib/style/themes/default';\n" +
      '| \n' +
      "| @pro-core-field-dropdown: ~'@{ant-prefix}-pro-core-field-dropdown';\n" +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-utils/es/components/FiledDropdown/index.js 10:0-22\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-utils/es/index.js\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/BasicLayout.js\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/index.js\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/index.js',
    '/tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-utils/es/components/FieldLabel/index.less 1:0\n' +
      "Module parse failed: Unexpected character '@' (1:0)\n" +
      'You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n' +
      "> @import (reference) '~antd/lib/style/themes/default';\n" +
      '| \n' +
      "| @pro-core-field-label: ~'@{ant-prefix}-pro-core-field-label';\n" +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-utils/es/components/FieldLabel/index.js 10:0-22\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-utils/es/index.js\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/BasicLayout.js\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/node_modules/@ant-design/pro-layout/es/index.js\n' +
      ' @ /tmp/tmp-build/packages/build-@ant-designpro-layout-EtU/index.js'
  ]
}

```

**Comment by pastelsky** [comment]
This specific missing-loader failure is resolved in the current build configuration. The current  Rspack configuration includes an explicit  rule using , so the old  error attributed to an absent less loader is no longer representative of the active pipeline.
