### ISSUE TITLE
<error-name>: <package-name> fails to <condition>

### ISSUE THREAD

**Issue by ksenginew** [pastelsky/bundlephobia#607]
## Package name
Vite

### Entire (stringified) error that I see in my browser console

```
main.bundle.js from Terser Invalid assignment [main.bundle.js:46116,17] at js_error (/var/www/bundlephobia/node_modules/terser/dist/bundle.min.js:550:11) at croak (/var/www/bundlephobia/node_modules/terser/dist/bundle.min.js:1274:9) at maybe_assign (/var/www/bundlephobia/node_modules/terser/dist/bundle.min.js:3443:13) at expression (/var/www/bundlephobia/node_modules/terser/dist/bundle.min.js:3452:24) at simple_statement (/var/www/bundlephobia/node_modules/terser/dist/bundle.min.js:1583:55) at statement (/var/www/bundlephobia/node_modules/terser/dist/bundle.min.js:1369:47) at _embed_tokens_wrapper (/var/www/bundlephobia/node_modules/terser/dist/bundle.min.js:1339:26) at block_ (/var/www/bundlephobia/node_modules/terser/dist/bundle.min.js:2172:20) at statement (/var/www/bundlephobia/node_modules/terser/dist/bundle.min.js:1403:29) at _embed_tokens_wrapper (/var/www/bundlephobia/node_modules/terser/dist/bundle.min.js:1339:26)
```

---
Thanks 👍 for this great tool. I would like to help with this issue.

**Comment by pastelsky** [comment]
This report is no longer reproducible against the current minification path. The current  pipeline uses Rspack with its Oxc-based JavaScript minimizer, not the Terser path named in this report, so the cited Terser  failure cannot occur in the current implementation.
