### ISSUE TITLE
<error-name>: <package-name> fails to <condition>

### ISSUE THREAD

**Issue by stefanobartoletti** [pastelsky/bundlephobia#833]
## Package name

@stefanobartoletti/nuxt-social-share

### Entire (stringified) error that I see in my browser console

`
0.bundle.js from Terser "module" is redeclared [0.bundle.js:18,6] at js_error (/var/www/bundlephobia/node_modules/terser/dist/bundle.min.js:545:11) at TreeWalker.visit (/var/www/bundlephobia/node_modules/terser/dist/bundle.min.js:11578:17) at TreeWalker._visit (/var/www/bundlephobia/node_modules/terser/dist/bundle.min.js:6641:24) at AST_SymbolConst._walk (/var/www/bundlephobia/node_modules/terser/dist/bundle.min.js:3779:24) at AST_VarDef.<anonymous> (/var/www/bundlephobia/node_modules/terser/dist/bundle.min.js:5036:23) at TreeWalker._visit (/var/www/bundlephobia/node_modules/terser/dist/bundle.min.js:6645:21) at AST_VarDef._walk (/var/www/bundlephobia/node_modules/terser/dist/bundle.min.js:5035:24) at AST_Const.<anonymous> (/var/www/bundlephobia/node_modules/terser/dist/bundle.min.js:4973:32) at TreeWalker._visit (/var/www/bundlephobia/node_modules/terser/dist/bundle.min.js:6645:21) at AST_Const._walk (/var/www/bundlephobia/node_modules/terser/dist/bundle.min.js:4970:24)
`

https://bundlephobia.com/package/@stefanobartoletti/nuxt-social-share

**Comment by pastelsky** [comment]
Closing as completed: the current build pipeline uses Rspack with the Oxc minifier rather than the old Terser path that raised the module-redeclaration error.
