### ISSUE TITLE
BuildError: @hellhub-collective/cli fails to build

### ISSUE THREAD

**Issue by fabio-nettis** [pastelsky/bundlephobia#868]
## Package name

[@hellhub-collective/cli](https://github.com/hellhub-collective/cli)

### Entire (stringified) error that I see in my browser console

```
"main.bundle.js from Terser
Private field must be used in an enclosing class [main.bundle.js:61,0]
    at js_error (/var/www/bundlephobia/node_modules/terser/dist/bundle.min.js:545:11)
    at croak (/var/www/bundlephobia/node_modules/terser/dist/bundle.min.js:1269:9)
    at statement (/var/www/bundlephobia/node_modules/terser/dist/bundle.min.js:1377:17)
    at _embed_tokens_wrapper (/var/www/bundlephobia/node_modules/terser/dist/bundle.min.js:1334:26)
    at block_ (/var/www/bundlephobia/node_modules/terser/dist/bundle.min.js:2173:20)
    at _function_body (/var/www/bundlephobia/node_modules/terser/dist/bundle.min.js:2085:21)
    at function_ (/var/www/bundlephobia/node_modules/terser/dist/bundle.min.js:1727:20)
    at expr_atom (/var/www/bundlephobia/node_modules/terser/dist/bundle.min.js:2518:24)
    at maybe_unary (/var/www/bundlephobia/node_modules/terser/dist/bundle.min.js:3405:19)
    at expr_ops (/var/www/bundlephobia/node_modules/terser/dist/bundle.min.js:3456:24)"
```

**Comment by pastelsky** [comment]
Closing as completed: the current build pipeline uses Rspack with the Oxc minifier rather than the old Terser path that raised the private-field parsing error.
